### ISSUE TITLE
Accept self signed certificates

### ISSUE THREAD

**Issue by fauust** [zaquestion/lab#152]
Hi,
is it possible to configure lab to accept self signed certificates?

This is the error:
`mrList.go:38: Get https:/api/v4/projects/<project>: x509: certificate signed by unknown authority`

**Comment by zaquestion** [comment]
@fauust This is something we can probably support. It should be simple enough to allow a configuration option to reference a cert file. At the same time can probably add an option to ignore cert failures.

**Comment by fauust** [comment]
@zaquestion or it is maybe easier to do something link the **wget** `--no-check-certificate` option or
the **curl** `-k, --insecure` option.

**Comment by tydavis** [comment]
I humbly offer my certpool / http client library: https://github.com/tydavis/gobundledhttp

I'm looking into the best way to add to the cert pool on-connect and permanently trust/store it.

**Comment by zaquestion** [comment]
@tydavis looks solid to me, I'm not sure how to use it for self signed certs, but that's largely due to me not being very familiar with actually handling that.

Am I correct in thinking the user would reference a personal cert file?

The insecure client would be immediately handy, we can probably update this function to accept an http client and just pass it through
https://github.com/zaquestion/lab/blob/master/main.go#L65

We'll wanna add a config option, that can just go anywhere for the moment. The config is pretty easy to access with viper. I'll need to think about the overall config structure a bit w.r.t. some other feature requests before any merge. Thoughts appreciated.

**Comment by darkmattercoder** [comment]
What about that issue? Is there a config option for accepting self signed certs? I want to use lab with our corporate instance which uses a self-signed cert.

**Comment by zaquestion** [comment]
@darkmattercoder It should be easy enough to create a config option to allow skipping the certificate check (`--insecure` option mentioned above). Would that work for your purposes?

**Comment by zaquestion** [comment]
@tydavis was working on adding actual support for custom certs, so I had opt'd to see that come in and not add the insecure option, but at this point I don't think that's coming.

**Comment by darkmattercoder** [comment]
Sure, I'm fine with a simple skip.

**Comment by tydavis** [comment]
Sorry -- I never got around to implementing

**Comment by gaving** [comment]
Been burned by this in corporate land, does anybody have a workaround?

**Comment by zaquestion** [comment]
@darkmattercoder @gaving I added config/logic to allow skipping tls verification here: https://github.com/zaquestion/lab/pull/354

Not yet merged, but will bring in and release today after it clears tests.

I also added some code to allow passing in custom certificates. I believe it should work as I've used the logic before, but I didn't actually test that stuff, so let me know if anyone tries it. 


To disable tls verification
```
"tls" = {
  "skip_verify" = true
}
```

to add your own certs (example file names)
```
"tls" = {
  "ca" = /path/to/server.pem
  "cert" = /path/to/client.pem
  "key" = /path/to/client-key.pem
}
```

In theory I believe it's possible to install the self signed root ca into your system and obviate the need for any config changes, but I haven't tested that either... If I was going to test it, I'd use https://github.com/FiloSottile/mkcert to generate and install certs.

Will leave this ticket open until either I or someone else test using custom certs with lab using the above approaches.

**Comment by zaquestion** [comment]
@fauust `v0.17.0` released with #354

**Comment by darkmattercoder** [comment]
Well, thank you much for your effort. 

I configured it with

```"tls" = {
  "skip_verify" = true
}```
 but I still get the same error. The configuration is read successfully as I first tried 

```"tls" = {
  "skip_verify" = "true"
}```

which then gave me an error because the "interface got string not bool" or similar.

Any ideas how to further debug?

**Comment by fauust** [comment]
> @fauust `v0.17.0` released with #354

Thanks! I will try this ASAP.

**Comment by gaving** [comment]
@zaquestion Awesome! Will give this a shot and let you know.

**Comment by gaving** [comment]
Similar result to @darkmattercoder at this end...

**Comment by zaquestion** [comment]
@darkmattercoder If you're willing to try another test would you mind building lab off https://github.com/zaquestion/lab/tree/tls_skip_test and seeing if it works. I don't have a test environment for this atm, but I can see the values properly getting passed through to the `http.Client` we're passing through to the `go-gitlab` api.

The branch I just pasted attempts to set `skipVerify` on the default transport, if that works it probably mean that somewhere in the `go-gitlab` library they aren't using the provided `http.Client` (or possibly somewhere in lab we aren't going through our client, but I don't think that's the case. In any case the test will indicate something.

This config is correct
```
"tls" = {
  "skip_verify" = true
}
```

**Comment by darkmattercoder** [comment]
I will do that test, promised. However I am off my office for the next three weeks, so I think it will not happen before.

**Comment by gaving** [comment]
@zaquestion 

Had a go off the `tls_skip_test` branch, pasted my result here:-

https://gist.github.com/gaving/18b358e569a8e0817b179d11d8af57a2

Getting the same error.

Any further debugging I can try?

**Comment by zaquestion** [comment]
@gaving That revealed the issue, evidently I'm the asshole

https://github.com/zaquestion/lab/blob/master/main.go#L163

To automatically get the user without it being specified in the config I instantiate the gitlab client manually at the above line (shown in the error you posted) it happens before the actual lab client is created. Thanks for the assist! I should have a working solution out today

**Comment by gaving** [comment]
@zaquestion

No worries, cheers for looking into this! 👏

**Comment by zaquestion** [comment]
This should fix it https://github.com/zaquestion/lab/pull/359

@gaving if you have a moment would you mind trying https://github.com/zaquestion/lab/tree/tls_skip_fix just to be sure.

**Comment by gaving** [comment]
@zaquestion

No problem, GMT here so will try it first thing tomorrow in work!

**Comment by gaving** [comment]
@zaquestion 

Built fresh image off `tls_skip_fix` branch:-

![image](https://user-images.githubusercontent.com/43741/71065119-774be780-2168-11ea-8f09-a6ccf43df4e3.png)

Seems to not like the config any more? Tried removing the tls but still get the same error.

```
panic: interface conversion: interface {} is nil, not string
goroutine 1 [running]:main.loadConfig(0x0, 0x0, 0xec9fc0, 0xc000000180, 0xc00010bf50, 0x4071bf, 0xc000086058) 
/go/src/app/main.go:129 +0x11a2main.main() 
/go/src/app/main.go:186 +0x92
```

**Comment by zaquestion** [comment]
Oops, dumb mistake I thought I tested, but actually my own `lab.hcl` had that value set. Just pushed a fix, this time for sure!

**Comment by gaving** [comment]
@zaquestion 

Definitely pushed? Same error... but had to `git reset --hard origin/tls_skip_fix` due to some diverging branches.

```
docker run -it -v $(pwd)/config:/root/.config lab:latest
2019/12/18 11:10:41 main.go:178: Get https://git.compant.local//api/v4/user: x509: certificate signed by unknown authority
```

**Comment by zaquestion** [comment]
Yeah for sure, I did rebase the commits so thats why you had to do that, probably should have waited on that.... I guess I'll just need to get gitlab going locally with https. You defs have the new code because the error line has moved in alignment with the changes... Errg sorry this is taking so long.

**Comment by gaving** [comment]
Ah no worries, give me a shout if you want any more testing - it must be difficult if you don't have a test setup.

I'd poke about myself but my Go knowledge is non existent! 🤣

**Comment by zaquestion** [comment]
hmm, I'm seeing it work for me, it turns out getting this going locally isn't that bad

docker run for gitlab with tls
```
docker run --detach   --hostname localhost   --env GITLAB_OMNIBUS_CONFIG="external_url 'https://localhost'; gitlab_rails['lfs_enabled'] = true;"  --publish 443:443 --publish 80:80 --publish 22:22   --name gitlab   --restart always   --volume /srv/gitlab/config:/etc/gitlab   --volume /srv/gitlab/logs:/var/log/gitlab   --volume /srv/gitlab/data:/var/opt/gitlab   gitlab/gitlab-ce:latest
```

config
```
"core" = {
  "host" = "https://localhost"

  "token" = "uQWa2BxLVuzpuCxHDjEz"
  "user" = "test"
}

"tls" = {
  "skip_verify" = true
}
```

bad project, but successfully skipping verification
```
$ lab mr list
2019/12/18 10:29:14 mr_list.go:47: gitlab project not found, verify you have access to the requested resource
```
reproduced with skip_verify set to false
```
$ lab mr list
2019/12/18 10:29:44 mr_list.go:47: Get https://localhost/api/v4/projects/zaquestion%2Flab: x509: certificate signed by unknown authority
```

@gaving you might try setting the user in your config to get past that initial error, it also speeds lab up a bit. That said, I'm gonna at least release a patch with these change, perhaps try again outside docker once it's out

**Comment by gaving** [comment]
@zaquestion 

Interesting, I wonder if it's specific to my setup in the case.

I'll have another play tomorrow and try setting user.... cheers.

**Comment by zaquestion** [comment]
The release is out as well https://github.com/zaquestion/lab/releases/tag/v0.17.2

**Comment by gaving** [comment]
@zaquestion 

🎉🎉🎉

Release seems to be working perfectly at this end.

![image](https://user-images.githubusercontent.com/43741/71154835-5c46a980-2234-11ea-9bbf-7bafc3d9380d.png)

Thanks for sorting this, not sure why inside Docker made any difference but glad to have it working now!

**Comment by darkmattercoder** [comment]
Works for me as well now. Sorry for the late reply, but life happened ;-) 

In my opinion you can close here.

**Comment by faruryo** [comment]
Hi,

It looks like skip_verify is not working in GitLab CI.

Perhaps you need to specify tlsSkipVerify outside of the config file because GitLab CI has returned in the case of GitLab CI before viper.ReadInConfig() in main.go's loadConfig().
https://github.com/zaquestion/lab/blob/master/main.go#L68

Is there a workaround?

**Comment by faruryo** [comment]
Self-resolved.
I could use skip_verify by using environment variables instead of configuration files.

`export LAB_TLS_SKIP_VERIFY=false`

**Comment by prarit** [comment]
Yes, this appears broken in latest tip.  I think it might be something with using .hcl files and viper.

**Comment by bmeneguele** [comment]
The config file infrastructure had a good overhaul at the beginning of 2021.
Where @faruryo 's issue seems to be resolved. I'm going to close this issue.
But please, feel free to re-open the issue if needed.
